users/urls.py
from django.urls import path

from .views import accounts

app_name = 'users'
urlpatterns = [
    path('signup/', accounts.signup, name='signup'),
    path(r'^signin/$', accounts.SigninViewClass.as_view(), name='signin'),
    path(r'^signin/(?P<next>\w+)$', accounts.SigninViewClass.as_view(), name='signin'),
    path('signout/', accounts.SignoutViewClass.as_view(), name='signout'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('searches.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/forms/registration_form.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from users.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(required=True,
                                label=_('Password', ),
                                strip=False,
                                help_text=password_validation.password_validators_help_text_html(),
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control", "autocomplete": "new-password"}), )
    password2 = forms.CharField(required=True,
                                label=_("Password confirmation"),
                                strip=False,
                                help_text=_("Enter the same password as before, for verification."),
                                widget=forms.PasswordInput(
                                    attrs={"class": "form-control", "autocomplete": "new-password"}), )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.error_messages["already_taken"] = _("This account is already taken.")

    def get_already_taken_error(self):
        return ValidationError(self.error_messages['already_taken'],
                               code='already_taken',
                               params={'email': UserProfile._meta.get_field(UserProfile.USERNAME_FIELD)})

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if UserProfile.objects.filter(email=email).exists():
            raise self.get_already_taken_error()
        return email

    def _post_clean(self):
        super()._post_clean()
        password = self.cleaned_data.get("password2")
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except ValidationError as error:
                self.add_error("password1", error)

    class Meta:
        model = UserProfile
        fields = ("email",)

templates/_profile_dropdown.html
<style>
    .dropdown-menu {
        position: absolute;
        display: none;
        {#background-color: #212529!important;#}
    }
    .dropdown-item {
        {#color: #ddd !important;#}
    }
    .dropdown:hover .dropdown-toggle {
        opacity: 0;
    }
    .dropdown:hover .dropdown-menu {
        display: block;
        animation: fadeIn 1s;
    }
    {#.dropdown-menu .dropdown-item:hover { background-color: #414141 !important;}#}


    @keyframes fadeIn {
      0% { opacity: 0; }
      100% { opacity: 1; }
    }
</style>
<div class="d-flex justify-content-end dropdown">
    <img src="../static/profile-avatar.png"
         id="profile-pic-dropdown-toogle"
         class="rounded-circle w-25 h-25 dropdown-toggle"
         alt="..."
         aria-expanded="false">
    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="profile-pic-dropdown-toogle">
        <li class="dropdown-header d-flex justify-content-end">
            <img src="../static/profile-avatar.png"
                 class="rounded-circle w-25 h-50"
                 alt="..."
                 aria-expanded="false">
        </li>
        <li><a class="dropdown-item" href="#">Account</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="{% url "users:signout" %}">Logout</a></li>
    </ul>

</div>

templates/_sign_options_dropdown.html
<div class="d-flex justify-content-end">
    <div class="col dropdown">
        <button class="btn btn-dark text-decoration-none"
                id="signin-modal-toggle"
                data-bs-toggle="modal"
                data-bs-target="#signin-modal"
                aria-expanded="false">
            Sign in
        </button>
    </div>
    <div class="col">
        <a class="btn btn-outline-light" href="{% url "users:signup" %}">Sign up</a>
    </div>

</div>
<!-- Signin Modal -->
<div class="modal fade" id="signin-modal" aria-labelledby="signin-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                Sign in on Universal SMC
            </div>
            <form method="post" action="{% url "users:signin" %}" class="px-4 py-3">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-floating mb-3">
                        <input type="email" class="form-control" id="id_email" name="email" autofocus>
                        <label for="id_email">Email</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="id_password" name="password" autocomplete="current-password">
                        <label for="id_password">Password</label>
                    </div>
                    <div class="d-flex flex-column justify-content-center">
                        <button type="submit" class="btn btn-success">Sign in</button>
                        <p class="text-center mt-2">New here? <a class="text-decoration-none"
                                                                 href="{% url "users:signup" %}">Create an account</a>
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include "styles.html" %}
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% include "scripts.html" %}
{% include "menu.html" %}
<div id="content" class="container mt-3">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/menu.html
<div class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="col-10">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">Contact</a>
                </li>
            </ul>
        </div>
        <div class="col-2">
            {% if user.is_authenticated %}
                {% include "_profile_dropdown.html" %}
            {% else %}
                {% include "_sign_options_dropdown.html" %}
            {% endif %}
        </div>
    </div>
</div>

templates/scripts.html
<script src="/static/bootstrap-5.0.2-dist/js/bootstrap.bundle.min.js"></script>

templates/styles.html
<link href="/static/bootstrap-5.0.2-dist/css/bootstrap.min.css" media="all" rel="stylesheet">