searches/urls.py
from django.urls import path

from . import views

app_name = 'searches'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.search, name='get_results'),
    path('create/', views.create, name='create')
]

users/urls.py
from django.urls import path

from .views import accounts

app_name = 'users'
urlpatterns = [
    path('signup/', accounts.signup, name='signup'),
    path(r'^signin/$', accounts.SigninViewClass.as_view(), name='signin'),
    path(r'^signin/(?P<next>\w+)$', accounts.SigninViewClass.as_view(), name='signin'),
    path('signout/', accounts.SignoutViewClass.as_view(), name='signout'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('searches.urls')),
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
]

searches/models/search.py
from django.db import models


class Search(models.Model):
    keywords = models.CharField(max_length=200, null=False)
    customer_ip = models.CharField(max_length=30, null=True)
    issued_at = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return f"{self.keywords} issued at: {self.issued_at.strftime('%Y-%m-%d %H-%M')}"

webapp/searchs/models.py
from django.db import models

# Create your models here.

searches/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .decorators.fetch_request_ipaddress import fetch_request_ipaddress

# Create your views here.
from .models import Search

@login_required #TODO: comentar para trabajar en feature de lista de busquedas
def index(request):
    s_list = Search.objects.all()
    return render(request, 'index/show.html', context={'items': s_list})


@login_required #TODO: comentar para trabajar en feature de lista de busquedas
def search(request):
    return render(request, 'results/show.html',
                  context={'status': 200, 'message': f'your message: {request.POST["query-item"]}'})


@login_required #TODO: comentar para trabajar en feature de lista de busquedas
@fetch_request_ipaddress
def create(request):
    if request.POST:
        new_search = Search(
            keywords=request.POST["query-item"],
            customer_ip=request.ip_address)
        new_search.save()
        return redirect(to="searches:index")

searches/templates/index/show.html
{% extends "base.html" %}

{% block title %}Consultas{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'searches:create' %}">
        {% csrf_token %}
        <input name="query-item" type="text" placeholder="type Part number or keyword">
        <input type="submit" value="search">
    </form>

    <div>
        <h2>Consultas realizadas</h2>
        <ul>
            {% for i in items %}
                <li>
                    <div>
                        <label>Keywords</label>
                        <p>{{ i.keywords }}</p>
                        <p>issued from: {{ i.customer_ip }}</p>
                        <p>issued at: {{ i.issued_at }}</p>
                    </div>
                </li>
            {% endfor %}

        </ul>
    </div>

{% endblock %}